name: pests
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^3.0.0
  font_awesome_flutter: ^8.6.0


  firebase_core: ^1.1.0

  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.6
  google_sign_in: ^4.1.4


  provider: ^4.0.4
  location: ^4.1.1
  google_maps_flutter: ^2.0.5
  email_validator: ^1.0.0
  flutter_spinkit: ^4.1.2
  cached_network_image: ^3.0.0
  flutter_datetime_picker: ^1.5.0
  intl: ^0.17.0
  toast: ^0.1.5
  image_picker: ^0.8.1+3
  flutter_offline: "^0.3.0"
  flutter_svg: ^0.22.0

  mercado_pago_mobile_checkout: ^0.1.0


  flutter_localizations: # Add this line
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/img/splascreen.jpg
    - assets/img/slider1.jpg
    - assets/img/producto.jpg
    - assets/img/vet-clinic.png
    - assets/img/pet-house.png
    - assets/img/hairdressing.png
    - assets/img/heart.png
    - assets/img/Banner.jpg
    - assets/img/mascota.jpg
    - assets/img/sin-mascota.png
    - assets/img/manzana.svg
    - assets/img/actividad.svg


  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf

    - family: SFProDisplay-Regular
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf

    - family: Dunkin
      fonts:
        - asset: assets/fonts/Dunkin.otf

    - family: DunkinBold
      fonts:
        - asset: assets/fonts/Dunkin Bold.otf

    - family: DBicons
      fonts:
        - asset: assets/icons/DBicons.ttf

    - family: heat
      fonts:
        - asset: assets/icons/heat.ttf

    - family: addCircular
      fonts:
        - asset: assets/icons/addCircular.ttf